eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 9001
spring:
  application:
    name: cloud-zuul

zuul:
  routes:
    api-a:
      path: /cloud-feign/**
      serviceId: cloudfeign
    api-b:
      path: /cloud-ribbon/**
      serviceId: cloud-ribbon